### ISSUE TITLE
Using this as a dependency in ops

### ISSUE THREAD

**Issue by kephale** [imagej/imagej-mesh#2]
@ctrueden would that be an problem? I ask because this might be a good (temporary?) home for the Mesh data structure.

**Comment by ctrueden** [comment]
I am OK with iterating on the mesh data structure here, although I think it needs to live in `imagej-common` for real. Alternately, perhaps better and easier would be to rename this repository to `imagej-mesh` and having both the data structure _and_ associated I/O plugins in one repo here. (I am just pedantic about repos named `<foo>-plugins-<bar>` having anything besides their stated plugins, or being used as dependencies anywhere.) What do you think?

**Comment by ctrueden** [comment]
OK, I propose the following plan:

1. Rename this repository to `imagej-mesh`.
2. Add any needed dependencies to make meshes work nicely, etc.
3. Add it as a dependency in `imagej-ops`.
4. Profit.

@kephale @rimadoma Good?

**Comment by kephale** [comment]
Brilliant!

**Comment by ctrueden** [comment]
OK, I renamed it. I can imagine a future where someone complains that imagej-ops depends on imagej-mesh which depends on scifio, since we are conflating the data structures and I/O plugins here. But we can always recreate imagej-plugins-io-mesh again later and move the I/O plugins to it, if that causes real problems.

**Comment by rimadoma** [comment]
@ctrueden Scifio? You mean SciJava?

**Comment by ctrueden** [comment]
@rimadoma Ah, you're right! We agreed that mesh I/O would be SciJava `IOPlugin`s directly, rather than SCIFIO.

Nonetheless, that could change in the future if we decide we need random access into "blocks" of mesh triangles or some such, e.g. for very large meshes. As long as we don't need any paging magic though, and can fit entire meshes into memory, it is not an issue.
